### ISSUE TITLE
Streaming output

### ISSUE THREAD

**Issue by jantman** [manheim/pack_rb#2]
Right now, the packer subcommands are run with Open3.capture3. The result of this is that no output is streamed to the console until the command finishes, which might take a long time. It would be nice if the output were both captured, and streamed to its original destination (STDOUT or STDERR). I have some sample code using Open3.popen3 that accomplishes this.

**Comment by jniesen** [comment]
You're right. I missed that. It should definitely capture and stream.

Did you want to take a shot at implementing this via pull request? If not, I'll have some time today when I can fix it.

**Comment by jantman** [comment]
@jniesen I'm about to start a PR to implement this and #3. I have the code in another internal/private gem, so it's already tested and working.

**Comment by jniesen** [comment]
Thank you.

**Comment by jantman** [comment]
@jniesen do we want to always stream the output, or do we want an option to not stream output, and keep the current behavior (only print output if the command fails)?

**Comment by jniesen** [comment]
I think, for now, always stream. We'll add an option if it becomes necessary.
