### ISSUE TITLE
Return output from packer build

### ISSUE THREAD

**Issue by jantman** [manheim/pack_rb#3]
Right now the output and exit status isn't returned from the packer build command. This means:

(1) There's no way to tell if the build succeeded or not, since the status isn't returned and it doesn't raise an exception on error.
(2) There's no way to extract information (i.e. generated AMI ID) from the output.

**Comment by jniesen** [comment]
Missed that one too. Saw your comment in #2. Look forward to the PR.

**Comment by jniesen** [comment]
Fixed with #6
