### ISSUE TITLE
Support Arch Linux / packer-io binary

### ISSUE THREAD

**Issue by jantman** [manheim/pack_rb#8]
On Arch Linux (and possibly some other distros??) packer.io is packaged as `packer-io` not `packer`, because of a conflict with a pre-existing `packer` binary.

We should support this, by finding the actual binary, and trying to find `packer-io` if `packer` doesn't exist.

I'm working on some code to do this.

**Comment by jniesen** [comment]
You can overwrite the packer command by passing in the `bin_path` to the packer binary that you want to be called.

I need to document this but you'd use it like:

``` ruby
packer = PackRb::Packer.new(tpl: template, machine_readable: true, bin_path: '/usr/bin/packer-io')
packer.build(debug: true)
```

**Comment by jantman** [comment]
But then I'd need the binary detection logic in whatever calls pack_rb... And if I use pack_rb in 5 projects, I'd need to duplicate that logic in all of them...
